### PR TITLE
Clean as build environment

### PR DESCRIPTION
**Pull request by taxigps**
1. remove folder libass and add folder patches.
2. add export function ass_set_line_position
3. add a patch

### CODE REVIEW

**Comment by taxigps** [comment]
@FernetMenta Is this right?

**Comment by FernetMenta** [comment]
yes. now I would update readme with instructions on where to download libass, that will be our mirrors, and how to patch it. Since this in for Windows do you recommend Power Shell?

**Comment by taxigps** [comment]
Can I merged this? You mean a Power Shell to build the libass.dll? who will rebuild the dll and upload to our mirror?

**Comment by FernetMenta** [comment]
> You mean a Power Shell to build the libass.dll? 

how exactly do you apply the patches? Windows cmd is not lacks lots of commands available on other systems. In this cases one can use power shell. patch cmd could .i.e. exacuted as pre-build command in VS.

> who will rebuild the dll and upload to our mirror?

I will try to build it once you have updated readme

**Comment by taxigps** [comment]
@FernetMenta add some scripts and update the readme. and need upload a harfbuzz-0.9.22.7z (build from https://github.com/blinkseb/harfbuzz) to our mirrors.

**Comment by FernetMenta** [comment]
> and need upload a harfbuzz-0.9.22.7z

why is that pre-built? what is in this archive?

**Comment by taxigps** [comment]
@FernetMenta we have harfbuzz-0.7.0.7z and harfbuzz-0.9.4.7z on our mirrors but their too old and can't use. so I create a new one (harfbuzz-0.9.22.7z) according to the readme in harfbuzz-0.9.4.7z:

```
harfbuzz Windows binaries for XBMC
To reproduce:

git clone git://github.com/blinkseb/harfbuzz.git
Open win32/harfbuzz.sln with Visual Studio.

** READ README.md before trying to build ** 

Build Release configuration

Run xbmc\package.bat to produce the final archive
```

**Comment by FernetMenta** [comment]
you did not answer my questions. the current readme suggests building harfbuzz so I would expect only code in this archive.

**Comment by FernetMenta** [comment]
what I am saying is that we need the sources of harfbuzz archived on our mirrors that we can patch and re-create the binaries at any time. I was able to build libass. I would add instructions to the readme how to build harfbuzz, then we upload the sources of harfbuzz and libass to our mirrors.

**Comment by Paxxi** [comment]
@FernetMenta  we don't keep sources around for prebuilt win32 libs afaik, we just make sure to document exact source and include any patches and build steps in the prebuilt package. @Karlson2k seem to be the one currently taking care that this is done.

**Comment by FernetMenta** [comment]
@Memphiz could you upload this to our mirrors? *.gz are sources, *.7z build-deps for win32

https://dl.dropboxusercontent.com/u/47522966/libass/libass-0.12.1-win32.7z
https://dl.dropboxusercontent.com/u/47522966/libass/libass-0.12.1.tar.gz

**Comment by FernetMenta** [comment]
@Paxxi yes we do, check the mirrors

**Comment by Memphiz** [comment]
@FernetMenta i can upload those this evening - though i have to agree with @Paxxi here. What is in the sources on our mirror is what is used by unified depends. For windows packages we normally don't pack the source there but do as @Paxxi said. There might be alot of source on the mirrors because we try to keep versions of used libs the same between win32 and unified depends though.

**Comment by FernetMenta** [comment]
so why do we have harfbuzz sources on our mirrors? it is only used for building libass for Windows. regardless what happens to the repositories we use, we must be able to rebuild all binaries.

EDIT: harfbuzz is also used for other platforms. I drop this from the links above. allthough I think we should keep the sources for the libs we use.

**Comment by Memphiz** [comment]
I agree - if someone from the windows front wants to make it right they would need to fetch all sources, upload them to the mirrors and update all win32 binary packages (their embedded README files at least) to reflect the new location of the source.

**Comment by taxigps** [comment]
@FernetMenta so how about this pull request? Is there anything need to do?

**Comment by FernetMenta** [comment]
yes. I don't think we should upload a binary to our mirrors just used to build another binary. please update this pr with instructions to build https://github.com/blinkseb/harfbuzz

**Comment by taxigps** [comment]
@FernetMenta done.

**Comment by FernetMenta** [comment]
thanks.

**Comment by FernetMenta** [comment]
@Memphiz plase wait with upload, I forgot to apply the patch
@taxigps the readme does not look nice after merge

**Comment by FernetMenta** [comment]
https://dl.dropboxusercontent.com/u/47522966/libass/libass-0.12.1.tar.gz
https://dl.dropboxusercontent.com/u/47522966/libass/libass-0.12.1-win32.7z

@Memphiz updated

**Comment by Memphiz** [comment]
@FernetMenta uploaded libass source to sources and libass 7z to win32

**Comment by FernetMenta** [comment]
thanks very much!

**Pull request merged**
