### PR TITLE
bump to version 0.12.1

### PR DESCRIPTION
**Pull request by taxigps**

### CODE REVIEW

**Comment by taxigps** [comment]
@MartijnKaijser who can review this?

**Comment by FernetMenta** [comment]
when mirroring a repository original commits should be preserved. Are there any patches we need to add to original reops of libass or harfbuzz? If this is not the case, we should drop this mirror completely.

**Comment by taxigps** [comment]
@FernetMenta need defined fopen_utf8 in ass_utils.c at least. which called by freetype246MT.lib.

**Comment by FernetMenta** [comment]
ok but this change needs to be a separate commit not hidden in this big update to 0.12.1 . we need to know why patches have been made and their source.

**Comment by Karlson2k** [comment]
@taxigps Freetype don't need `fopen_utf8` anymore. This patch can be removed.

**Comment by taxigps** [comment]
@Karlson2k I think freetype still need fopen_utf8 under windows platform. other wise kodi can't load fonts in some none english path.

**Comment by taxigps** [comment]
@FernetMenta that patch already in commit https://github.com/xbmc/libass/commit/01f9b0d4c5a5820b2d61324e46a70412dabeecf2

**Comment by FernetMenta** [comment]
yes, those 2 commits float on top of https://github.com/xbmc/libass/commits/master/libass and they should stay there after rebase of libass

**Comment by Karlson2k** [comment]
@taxigps
See https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIFontTTF.cpp#L100

**Comment by FernetMenta** [comment]
@Karlson2k why do we still use freetype 2.4.6 on Windows?

**Comment by taxigps** [comment]
@Karlson2k windows system use unicode not utf-8. so freetype need call fopen_utf8 witch trans utf-8 filename into unicode to open. see readme.txt in freetype-2.4.6-win32-3.7z

**Comment by Karlson2k** [comment]
@FernetMenta I think because it satisfy everybody since nobody asked for bump.

**Comment by Karlson2k** [comment]
@taxigps, could you please check code at my link?

**Comment by taxigps** [comment]
@Karlson2k so we load font in memory before call freetype. In this case, we should rebuild freetype-2.4.6-win32-3.7z to remove use of fopen_utf8.

**Comment by Karlson2k** [comment]
@taxigps We don't care if `fopen_utf8` is used or not.
It can be removed and not included for next builds.

**Comment by FernetMenta** [comment]
then I ask again :) is there anything added to libass. If not, the sources should be removed from this repo. for a small change a patch should do as well.

**Comment by taxigps** [comment]
@FernetMenta nothing added to libass now. but should add a libass.def file to exports functions in dll. and I want to add one patch in pull request #1 :)

**Comment by FernetMenta** [comment]
This repo should be a build environment for libass on VS, right? I would bring libass in line with the other dependencies. Means remove it from this repo and update the readme accordingly. You could add a patch folder to this repo and place the libass patches there.

**Comment by taxigps** [comment]
Yes, I think this repo just be a build environment for libass on VS now. And I need export function ass_set_line_position so kodi can call it to set subtitles position use setting "subtitles.align", how to do this now? and when can I add the patch in #1 ?

**Comment by FernetMenta** [comment]
remove folder libass, create a folder patches and place your patches in this folder. then update readme with build instructions.

**Comment by taxigps** [comment]
see #3

**Pull request closed without merging**
